// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ImagesController from "./images_controller"
application.register("images", ImagesController)

import QuantityController from "./quantity_controller"
application.register("quantity", QuantityController)

import RemovalsController from "./removals_controller"
application.register("removals", RemovalsController)
